# Site settings
title: SMS Ágil
email: contato@smsagil.com.br
description: "Campanhas de marketing com sms"
baseurl: ""
url: "http://smsagil.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

permalink: /:title/

# analytics:
#  provider: google
#  google:
#   tracking_id : 'UA-56019611-2'
